/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  integer,
  varchar,
  timestamp,
  numeric,
  jsonb,
  boolean,
  type AnyPgColumn,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'customer'])
export const enum_products_status = pgEnum('enum_products_status', [
  'draft',
  'published',
  'out-of-stock',
])
export const enum__products_v_version_status = pgEnum('enum__products_v_version_status', [
  'draft',
  'published',
  'out-of-stock',
])
export const enum_discounts_type = pgEnum('enum_discounts_type', ['percentage', 'fixedAmount'])
export const enum_discounts_applies_to = pgEnum('enum_discounts_applies_to', [
  'order',
  'products',
  'categories',
])
export const enum_orders_status = pgEnum('enum_orders_status', [
  'pending',
  'paid',
  'shipped',
  'delivered',
  'cancelled',
])
export const enum_reviews_voted_users_type = pgEnum('enum_reviews_voted_users_type', [
  'helpful',
  'notHelpful',
])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'schedulePublish',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'schedulePublish',
])

export const user_accounts = pgTable(
  'user_accounts',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    accountId: varchar('account_id').notNull(),
    providerId: varchar('provider_id').notNull(),
    accessToken: varchar('access_token'),
    refreshToken: varchar('refresh_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    scope: varchar('scope'),
    idToken: varchar('id_token'),
    password: varchar('password'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    user_accounts_user_id_idx: index('user_accounts_user_id_idx').on(columns.userId),
    user_accounts_provider_id_idx: index('user_accounts_provider_id_idx').on(columns.providerId),
    user_accounts_updated_at_idx: index('user_accounts_updated_at_idx').on(columns.updatedAt),
    user_accounts_created_at_idx: index('user_accounts_created_at_idx').on(columns.createdAt),
  }),
)

export const user_sessions = pgTable(
  'user_sessions',
  {
    id: serial('id').primaryKey(),
    userId: integer('user_id_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    token: varchar('token').notNull(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    ipAddress: varchar('ip_address'),
    userAgent: varchar('user_agent'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    user_sessions_user_id_idx: index('user_sessions_user_id_idx').on(columns.userId),
    user_sessions_token_idx: uniqueIndex('user_sessions_token_idx').on(columns.token),
    user_sessions_ip_address_idx: index('user_sessions_ip_address_idx').on(columns.ipAddress),
    user_sessions_updated_at_idx: index('user_sessions_updated_at_idx').on(columns.updatedAt),
    user_sessions_created_at_idx: index('user_sessions_created_at_idx').on(columns.createdAt),
  }),
)

export const user_verifications = pgTable(
  'user_verifications',
  {
    id: serial('id').primaryKey(),
    identifier: varchar('identifier').notNull(),
    value: varchar('value').notNull(),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    user_verifications_updated_at_idx: index('user_verifications_updated_at_idx').on(
      columns.updatedAt,
    ),
    user_verifications_created_at_idx: index('user_verifications_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const users_role = pgTable(
  'users_role',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_users_role('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('users_role_order_idx').on(columns.order),
    parentIdx: index('users_role_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_role_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    email: varchar('email').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    users_avatar_idx: index('users_avatar_idx').on(columns.avatar),
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
  }),
)

export const users_rels = pgTable(
  'users_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
  },
  (columns) => ({
    order: index('users_rels_order_idx').on(columns.order),
    parentIdx: index('users_rels_parent_idx').on(columns.parent),
    pathIdx: index('users_rels_path_idx').on(columns.path),
    users_rels_products_id_idx: index('users_rels_products_id_idx').on(columns.productsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_rels_parent_fk',
    }).onDelete('cascade'),
    productsIdFk: foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'users_rels_products_fk',
    }).onDelete('cascade'),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const products_images = pgTable(
  'products_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    alt: varchar('alt'),
  },
  (columns) => ({
    _orderIdx: index('products_images_order_idx').on(columns._order),
    _parentIDIdx: index('products_images_parent_id_idx').on(columns._parentID),
    products_images_image_idx: index('products_images_image_idx').on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const products_rating_distribution = pgTable(
  'products_rating_distribution',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    stars: numeric('stars'),
    count: numeric('count'),
  },
  (columns) => ({
    _orderIdx: index('products_rating_distribution_order_idx').on(columns._order),
    _parentIDIdx: index('products_rating_distribution_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_rating_distribution_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    title: varchar('title'),
    slug: varchar('slug'),
    description: jsonb('description'),
    shortDescription: varchar('short_description'),
    origin: integer('origin_id').references(() => origin.id, {
      onDelete: 'set null',
    }),
    deity: integer('deity_id').references(() => deities.id, {
      onDelete: 'set null',
    }),
    totalReviews: numeric('total_reviews'),
    averageRating: numeric('average_rating'),
    seo_title: varchar('seo_title'),
    seo_image: integer('seo_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    seo_description: varchar('seo_description'),
    seo_keywords: varchar('seo_keywords'),
    status: enum_products_status('status').default('draft'),
    featured: boolean('featured').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_products_status('_status').default('draft'),
  },
  (columns) => ({
    products_slug_idx: uniqueIndex('products_slug_idx').on(columns.slug),
    products_origin_idx: index('products_origin_idx').on(columns.origin),
    products_deity_idx: index('products_deity_idx').on(columns.deity),
    products_seo_seo_image_idx: index('products_seo_seo_image_idx').on(columns.seo_image),
    products_updated_at_idx: index('products_updated_at_idx').on(columns.updatedAt),
    products_created_at_idx: index('products_created_at_idx').on(columns.createdAt),
    products__status_idx: index('products__status_idx').on(columns._status),
  }),
)

export const products_rels = pgTable(
  'products_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    materialsID: integer('materials_id'),
    finishesID: integer('finishes_id'),
    categoriesID: integer('categories_id'),
    variantsID: integer('variants_id'),
  },
  (columns) => ({
    order: index('products_rels_order_idx').on(columns.order),
    parentIdx: index('products_rels_parent_idx').on(columns.parent),
    pathIdx: index('products_rels_path_idx').on(columns.path),
    products_rels_materials_id_idx: index('products_rels_materials_id_idx').on(columns.materialsID),
    products_rels_finishes_id_idx: index('products_rels_finishes_id_idx').on(columns.finishesID),
    products_rels_categories_id_idx: index('products_rels_categories_id_idx').on(
      columns.categoriesID,
    ),
    products_rels_variants_id_idx: index('products_rels_variants_id_idx').on(columns.variantsID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    materialsIdFk: foreignKey({
      columns: [columns['materialsID']],
      foreignColumns: [materials.id],
      name: 'products_rels_materials_fk',
    }).onDelete('cascade'),
    finishesIdFk: foreignKey({
      columns: [columns['finishesID']],
      foreignColumns: [finishes.id],
      name: 'products_rels_finishes_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'products_rels_categories_fk',
    }).onDelete('cascade'),
    variantsIdFk: foreignKey({
      columns: [columns['variantsID']],
      foreignColumns: [variants.id],
      name: 'products_rels_variants_fk',
    }).onDelete('cascade'),
  }),
)

export const _products_v_version_images = pgTable(
  '_products_v_version_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    alt: varchar('alt'),
    _uuid: varchar('_uuid'),
  },
  (columns) => ({
    _orderIdx: index('_products_v_version_images_order_idx').on(columns._order),
    _parentIDIdx: index('_products_v_version_images_parent_id_idx').on(columns._parentID),
    _products_v_version_images_image_idx: index('_products_v_version_images_image_idx').on(
      columns.image,
    ),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const _products_v_version_rating_distribution = pgTable(
  '_products_v_version_rating_distribution',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: serial('id').primaryKey(),
    stars: numeric('stars'),
    count: numeric('count'),
    _uuid: varchar('_uuid'),
  },
  (columns) => ({
    _orderIdx: index('_products_v_version_rating_distribution_order_idx').on(columns._order),
    _parentIDIdx: index('_products_v_version_rating_distribution_parent_id_idx').on(
      columns._parentID,
    ),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [_products_v.id],
      name: '_products_v_version_rating_distribution_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const _products_v = pgTable(
  '_products_v',
  {
    id: serial('id').primaryKey(),
    parent: integer('parent_id').references(() => products.id, {
      onDelete: 'set null',
    }),
    version_title: varchar('version_title'),
    version_slug: varchar('version_slug'),
    version_description: jsonb('version_description'),
    version_shortDescription: varchar('version_short_description'),
    version_origin: integer('version_origin_id').references(() => origin.id, {
      onDelete: 'set null',
    }),
    version_deity: integer('version_deity_id').references(() => deities.id, {
      onDelete: 'set null',
    }),
    version_totalReviews: numeric('version_total_reviews'),
    version_averageRating: numeric('version_average_rating'),
    version_seo_title: varchar('version_seo_title'),
    version_seo_image: integer('version_seo_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    version_seo_description: varchar('version_seo_description'),
    version_seo_keywords: varchar('version_seo_keywords'),
    version_status: enum__products_v_version_status('version_status').default('draft'),
    version_featured: boolean('version_featured').default(false),
    version_updatedAt: timestamp('version_updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp('version_created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__products_v_version_status('version__status').default('draft'),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean('latest'),
    autosave: boolean('autosave'),
  },
  (columns) => ({
    _products_v_parent_idx: index('_products_v_parent_idx').on(columns.parent),
    _products_v_version_version_slug_idx: index('_products_v_version_version_slug_idx').on(
      columns.version_slug,
    ),
    _products_v_version_version_origin_idx: index('_products_v_version_version_origin_idx').on(
      columns.version_origin,
    ),
    _products_v_version_version_deity_idx: index('_products_v_version_version_deity_idx').on(
      columns.version_deity,
    ),
    _products_v_version_seo_version_seo_image_idx: index(
      '_products_v_version_seo_version_seo_image_idx',
    ).on(columns.version_seo_image),
    _products_v_version_version_updated_at_idx: index(
      '_products_v_version_version_updated_at_idx',
    ).on(columns.version_updatedAt),
    _products_v_version_version_created_at_idx: index(
      '_products_v_version_version_created_at_idx',
    ).on(columns.version_createdAt),
    _products_v_version_version__status_idx: index('_products_v_version_version__status_idx').on(
      columns.version__status,
    ),
    _products_v_created_at_idx: index('_products_v_created_at_idx').on(columns.createdAt),
    _products_v_updated_at_idx: index('_products_v_updated_at_idx').on(columns.updatedAt),
    _products_v_latest_idx: index('_products_v_latest_idx').on(columns.latest),
    _products_v_autosave_idx: index('_products_v_autosave_idx').on(columns.autosave),
  }),
)

export const _products_v_rels = pgTable(
  '_products_v_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    materialsID: integer('materials_id'),
    finishesID: integer('finishes_id'),
    categoriesID: integer('categories_id'),
    variantsID: integer('variants_id'),
  },
  (columns) => ({
    order: index('_products_v_rels_order_idx').on(columns.order),
    parentIdx: index('_products_v_rels_parent_idx').on(columns.parent),
    pathIdx: index('_products_v_rels_path_idx').on(columns.path),
    _products_v_rels_materials_id_idx: index('_products_v_rels_materials_id_idx').on(
      columns.materialsID,
    ),
    _products_v_rels_finishes_id_idx: index('_products_v_rels_finishes_id_idx').on(
      columns.finishesID,
    ),
    _products_v_rels_categories_id_idx: index('_products_v_rels_categories_id_idx').on(
      columns.categoriesID,
    ),
    _products_v_rels_variants_id_idx: index('_products_v_rels_variants_id_idx').on(
      columns.variantsID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [_products_v.id],
      name: '_products_v_rels_parent_fk',
    }).onDelete('cascade'),
    materialsIdFk: foreignKey({
      columns: [columns['materialsID']],
      foreignColumns: [materials.id],
      name: '_products_v_rels_materials_fk',
    }).onDelete('cascade'),
    finishesIdFk: foreignKey({
      columns: [columns['finishesID']],
      foreignColumns: [finishes.id],
      name: '_products_v_rels_finishes_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: '_products_v_rels_categories_fk',
    }).onDelete('cascade'),
    variantsIdFk: foreignKey({
      columns: [columns['variantsID']],
      foreignColumns: [variants.id],
      name: '_products_v_rels_variants_fk',
    }).onDelete('cascade'),
  }),
)

export const variants_images = pgTable(
  'variants_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    alt: varchar('alt').notNull(),
  },
  (columns) => ({
    _orderIdx: index('variants_images_order_idx').on(columns._order),
    _parentIDIdx: index('variants_images_parent_id_idx').on(columns._parentID),
    variants_images_image_idx: index('variants_images_image_idx').on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [variants.id],
      name: 'variants_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const variants = pgTable(
  'variants',
  {
    id: serial('id').primaryKey(),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    size: integer('size_id')
      .notNull()
      .references(() => sizes.id, {
        onDelete: 'set null',
      }),
    height: numeric('height').notNull(),
    width: numeric('width').notNull(),
    depth: numeric('depth').notNull(),
    weight: numeric('weight').notNull(),
    color: integer('color_id')
      .notNull()
      .references(() => colors.id, {
        onDelete: 'set null',
      }),
    price: numeric('price').notNull(),
    sku: varchar('sku').notNull(),
    trackInventory: boolean('track_inventory').default(true),
    quantity: numeric('quantity').notNull().default('0'),
    lowStockThreshold: numeric('low_stock_threshold').default('5'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    variants_product_idx: index('variants_product_idx').on(columns.product),
    variants_size_idx: index('variants_size_idx').on(columns.size),
    variants_color_idx: index('variants_color_idx').on(columns.color),
    variants_sku_idx: uniqueIndex('variants_sku_idx').on(columns.sku),
    variants_updated_at_idx: index('variants_updated_at_idx').on(columns.updatedAt),
    variants_created_at_idx: index('variants_created_at_idx').on(columns.createdAt),
  }),
)

export const sizes = pgTable(
  'sizes',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    sizes_name_idx: uniqueIndex('sizes_name_idx').on(columns.name),
    sizes_updated_at_idx: index('sizes_updated_at_idx').on(columns.updatedAt),
    sizes_created_at_idx: index('sizes_created_at_idx').on(columns.createdAt),
  }),
)

export const materials = pgTable(
  'materials',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    materials_name_idx: uniqueIndex('materials_name_idx').on(columns.name),
    materials_updated_at_idx: index('materials_updated_at_idx').on(columns.updatedAt),
    materials_created_at_idx: index('materials_created_at_idx').on(columns.createdAt),
  }),
)

export const finishes = pgTable(
  'finishes',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    finishes_name_idx: uniqueIndex('finishes_name_idx').on(columns.name),
    finishes_updated_at_idx: index('finishes_updated_at_idx').on(columns.updatedAt),
    finishes_created_at_idx: index('finishes_created_at_idx').on(columns.createdAt),
  }),
)

export const deities = pgTable(
  'deities',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    description: jsonb('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    deities_name_idx: uniqueIndex('deities_name_idx').on(columns.name),
    deities_updated_at_idx: index('deities_updated_at_idx').on(columns.updatedAt),
    deities_created_at_idx: index('deities_created_at_idx').on(columns.createdAt),
  }),
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description'),
    parent: integer('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    categories_title_idx: uniqueIndex('categories_title_idx').on(columns.title),
    categories_parent_idx: index('categories_parent_idx').on(columns.parent),
    categories_updated_at_idx: index('categories_updated_at_idx').on(columns.updatedAt),
    categories_created_at_idx: index('categories_created_at_idx').on(columns.createdAt),
  }),
)

export const colors = pgTable(
  'colors',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    color: varchar('color').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    colors_name_idx: uniqueIndex('colors_name_idx').on(columns.name),
    colors_color_idx: uniqueIndex('colors_color_idx').on(columns.color),
    colors_updated_at_idx: index('colors_updated_at_idx').on(columns.updatedAt),
    colors_created_at_idx: index('colors_created_at_idx').on(columns.createdAt),
  }),
)

export const origin = pgTable(
  'origin',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    origin_name_idx: uniqueIndex('origin_name_idx').on(columns.name),
    origin_updated_at_idx: index('origin_updated_at_idx').on(columns.updatedAt),
    origin_created_at_idx: index('origin_created_at_idx').on(columns.createdAt),
  }),
)

export const discounts = pgTable(
  'discounts',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    requiresCode: boolean('requires_code').default(true),
    code: varchar('code'),
    type: enum_discounts_type('type').notNull(),
    percent: numeric('percent'),
    amount: numeric('amount'),
    appliesTo: enum_discounts_applies_to('applies_to').notNull().default('order'),
    minimumCartValue: numeric('minimum_cart_value'),
    startDate: timestamp('start_date', { mode: 'string', withTimezone: true, precision: 3 }),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    usageLimit: numeric('usage_limit'),
    usageCount: numeric('usage_count').default('0'),
    limitPerUser: numeric('limit_per_user').default('1'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    discounts_code_idx: uniqueIndex('discounts_code_idx').on(columns.code),
    discounts_updated_at_idx: index('discounts_updated_at_idx').on(columns.updatedAt),
    discounts_created_at_idx: index('discounts_created_at_idx').on(columns.createdAt),
  }),
)

export const discounts_rels = pgTable(
  'discounts_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    productsID: integer('products_id'),
    categoriesID: integer('categories_id'),
  },
  (columns) => ({
    order: index('discounts_rels_order_idx').on(columns.order),
    parentIdx: index('discounts_rels_parent_idx').on(columns.parent),
    pathIdx: index('discounts_rels_path_idx').on(columns.path),
    discounts_rels_products_id_idx: index('discounts_rels_products_id_idx').on(columns.productsID),
    discounts_rels_categories_id_idx: index('discounts_rels_categories_id_idx').on(
      columns.categoriesID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [discounts.id],
      name: 'discounts_rels_parent_fk',
    }).onDelete('cascade'),
    productsIdFk: foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'discounts_rels_products_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'discounts_rels_categories_fk',
    }).onDelete('cascade'),
  }),
)

export const orders_items = pgTable(
  'orders_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    quantity: numeric('quantity').notNull(),
    price: numeric('price').notNull(),
  },
  (columns) => ({
    _orderIdx: index('orders_items_order_idx').on(columns._order),
    _parentIDIdx: index('orders_items_parent_id_idx').on(columns._parentID),
    orders_items_product_idx: index('orders_items_product_idx').on(columns.product),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [orders.id],
      name: 'orders_items_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const orders = pgTable(
  'orders',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    total: numeric('total').notNull(),
    status: enum_orders_status('status').default('pending'),
    stripeSessionId: varchar('stripe_session_id'),
    shippingInfo: integer('shipping_info_id').references(() => shipping_info.id, {
      onDelete: 'set null',
    }),
    paymentInfo: integer('payment_info_id').references(() => payment_info.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    orders_user_idx: index('orders_user_idx').on(columns.user),
    orders_shipping_info_idx: index('orders_shipping_info_idx').on(columns.shippingInfo),
    orders_payment_info_idx: index('orders_payment_info_idx').on(columns.paymentInfo),
    orders_updated_at_idx: index('orders_updated_at_idx').on(columns.updatedAt),
    orders_created_at_idx: index('orders_created_at_idx').on(columns.createdAt),
  }),
)

export const shipping_info = pgTable(
  'shipping_info',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    addressName: varchar('address_name'),
    addressLine1: varchar('address_line1').notNull(),
    addressLine2: varchar('address_line2'),
    city: varchar('city').notNull(),
    state: varchar('state').notNull(),
    postalCode: varchar('postal_code').notNull(),
    country: varchar('country').notNull(),
    isDefault: boolean('is_default').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    shipping_info_user_idx: index('shipping_info_user_idx').on(columns.user),
    shipping_info_updated_at_idx: index('shipping_info_updated_at_idx').on(columns.updatedAt),
    shipping_info_created_at_idx: index('shipping_info_created_at_idx').on(columns.createdAt),
  }),
)

export const payment_info = pgTable(
  'payment_info',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    stripeCustomerId: varchar('stripe_customer_id').notNull(),
    stripePaymentMethodId: varchar('stripe_payment_method_id').notNull(),
    brand: varchar('brand'),
    last4: varchar('last4'),
    expMonth: numeric('exp_month'),
    expYear: numeric('exp_year'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payment_info_user_idx: index('payment_info_user_idx').on(columns.user),
    payment_info_updated_at_idx: index('payment_info_updated_at_idx').on(columns.updatedAt),
    payment_info_created_at_idx: index('payment_info_created_at_idx').on(columns.createdAt),
  }),
)

export const reviews_images = pgTable(
  'reviews_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    alt: varchar('alt'),
  },
  (columns) => ({
    _orderIdx: index('reviews_images_order_idx').on(columns._order),
    _parentIDIdx: index('reviews_images_parent_id_idx').on(columns._parentID),
    reviews_images_image_idx: index('reviews_images_image_idx').on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [reviews.id],
      name: 'reviews_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const reviews_voted_users = pgTable(
  'reviews_voted_users',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    type: enum_reviews_voted_users_type('type').notNull(),
  },
  (columns) => ({
    _orderIdx: index('reviews_voted_users_order_idx').on(columns._order),
    _parentIDIdx: index('reviews_voted_users_parent_id_idx').on(columns._parentID),
    reviews_voted_users_user_idx: index('reviews_voted_users_user_idx').on(columns.user),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [reviews.id],
      name: 'reviews_voted_users_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const reviews = pgTable(
  'reviews',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    verifiedPurchase: boolean('verified_purchase').default(false),
    rating: numeric('rating').notNull(),
    title: varchar('title'),
    comment: varchar('comment'),
    helpfulCount: numeric('helpful_count').default('0'),
    notHelpfulCount: numeric('not_helpful_count').default('0'),
    approved: boolean('approved').default(false),
    reply: jsonb('reply'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    reviews_user_idx: index('reviews_user_idx').on(columns.user),
    reviews_product_idx: index('reviews_product_idx').on(columns.product),
    reviews_updated_at_idx: index('reviews_updated_at_idx').on(columns.updatedAt),
    reviews_created_at_idx: index('reviews_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => ({
    _orderIdx: index('payload_jobs_log_order_idx').on(columns._order),
    _parentIDIdx: index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried').default('0'),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_jobs_completed_at_idx: index('payload_jobs_completed_at_idx').on(columns.completedAt),
    payload_jobs_total_tried_idx: index('payload_jobs_total_tried_idx').on(columns.totalTried),
    payload_jobs_has_error_idx: index('payload_jobs_has_error_idx').on(columns.hasError),
    payload_jobs_task_slug_idx: index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    payload_jobs_queue_idx: index('payload_jobs_queue_idx').on(columns.queue),
    payload_jobs_wait_until_idx: index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    payload_jobs_processing_idx: index('payload_jobs_processing_idx').on(columns.processing),
    payload_jobs_updated_at_idx: index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    payload_jobs_created_at_idx: index('payload_jobs_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'user-accountsID': integer('user_accounts_id'),
    'user-sessionsID': integer('user_sessions_id'),
    'user-verificationsID': integer('user_verifications_id'),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    productsID: integer('products_id'),
    variantsID: integer('variants_id'),
    sizesID: integer('sizes_id'),
    materialsID: integer('materials_id'),
    finishesID: integer('finishes_id'),
    deitiesID: integer('deities_id'),
    categoriesID: integer('categories_id'),
    colorsID: integer('colors_id'),
    originID: integer('origin_id'),
    discountsID: integer('discounts_id'),
    ordersID: integer('orders_id'),
    shippingInfoID: integer('shipping_info_id'),
    paymentInfoID: integer('payment_info_id'),
    reviewsID: integer('reviews_id'),
    'payload-jobsID': integer('payload_jobs_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_user_accounts_id_idx: index(
      'payload_locked_documents_rels_user_accounts_id_idx',
    ).on(columns['user-accountsID']),
    payload_locked_documents_rels_user_sessions_id_idx: index(
      'payload_locked_documents_rels_user_sessions_id_idx',
    ).on(columns['user-sessionsID']),
    payload_locked_documents_rels_user_verifications_id_idx: index(
      'payload_locked_documents_rels_user_verifications_id_idx',
    ).on(columns['user-verificationsID']),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_products_id_idx: index(
      'payload_locked_documents_rels_products_id_idx',
    ).on(columns.productsID),
    payload_locked_documents_rels_variants_id_idx: index(
      'payload_locked_documents_rels_variants_id_idx',
    ).on(columns.variantsID),
    payload_locked_documents_rels_sizes_id_idx: index(
      'payload_locked_documents_rels_sizes_id_idx',
    ).on(columns.sizesID),
    payload_locked_documents_rels_materials_id_idx: index(
      'payload_locked_documents_rels_materials_id_idx',
    ).on(columns.materialsID),
    payload_locked_documents_rels_finishes_id_idx: index(
      'payload_locked_documents_rels_finishes_id_idx',
    ).on(columns.finishesID),
    payload_locked_documents_rels_deities_id_idx: index(
      'payload_locked_documents_rels_deities_id_idx',
    ).on(columns.deitiesID),
    payload_locked_documents_rels_categories_id_idx: index(
      'payload_locked_documents_rels_categories_id_idx',
    ).on(columns.categoriesID),
    payload_locked_documents_rels_colors_id_idx: index(
      'payload_locked_documents_rels_colors_id_idx',
    ).on(columns.colorsID),
    payload_locked_documents_rels_origin_id_idx: index(
      'payload_locked_documents_rels_origin_id_idx',
    ).on(columns.originID),
    payload_locked_documents_rels_discounts_id_idx: index(
      'payload_locked_documents_rels_discounts_id_idx',
    ).on(columns.discountsID),
    payload_locked_documents_rels_orders_id_idx: index(
      'payload_locked_documents_rels_orders_id_idx',
    ).on(columns.ordersID),
    payload_locked_documents_rels_shipping_info_id_idx: index(
      'payload_locked_documents_rels_shipping_info_id_idx',
    ).on(columns.shippingInfoID),
    payload_locked_documents_rels_payment_info_id_idx: index(
      'payload_locked_documents_rels_payment_info_id_idx',
    ).on(columns.paymentInfoID),
    payload_locked_documents_rels_reviews_id_idx: index(
      'payload_locked_documents_rels_reviews_id_idx',
    ).on(columns.reviewsID),
    payload_locked_documents_rels_payload_jobs_id_idx: index(
      'payload_locked_documents_rels_payload_jobs_id_idx',
    ).on(columns['payload-jobsID']),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    'user-accountsIdFk': foreignKey({
      columns: [columns['user-accountsID']],
      foreignColumns: [user_accounts.id],
      name: 'payload_locked_documents_rels_user_accounts_fk',
    }).onDelete('cascade'),
    'user-sessionsIdFk': foreignKey({
      columns: [columns['user-sessionsID']],
      foreignColumns: [user_sessions.id],
      name: 'payload_locked_documents_rels_user_sessions_fk',
    }).onDelete('cascade'),
    'user-verificationsIdFk': foreignKey({
      columns: [columns['user-verificationsID']],
      foreignColumns: [user_verifications.id],
      name: 'payload_locked_documents_rels_user_verifications_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    productsIdFk: foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    variantsIdFk: foreignKey({
      columns: [columns['variantsID']],
      foreignColumns: [variants.id],
      name: 'payload_locked_documents_rels_variants_fk',
    }).onDelete('cascade'),
    sizesIdFk: foreignKey({
      columns: [columns['sizesID']],
      foreignColumns: [sizes.id],
      name: 'payload_locked_documents_rels_sizes_fk',
    }).onDelete('cascade'),
    materialsIdFk: foreignKey({
      columns: [columns['materialsID']],
      foreignColumns: [materials.id],
      name: 'payload_locked_documents_rels_materials_fk',
    }).onDelete('cascade'),
    finishesIdFk: foreignKey({
      columns: [columns['finishesID']],
      foreignColumns: [finishes.id],
      name: 'payload_locked_documents_rels_finishes_fk',
    }).onDelete('cascade'),
    deitiesIdFk: foreignKey({
      columns: [columns['deitiesID']],
      foreignColumns: [deities.id],
      name: 'payload_locked_documents_rels_deities_fk',
    }).onDelete('cascade'),
    categoriesIdFk: foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    colorsIdFk: foreignKey({
      columns: [columns['colorsID']],
      foreignColumns: [colors.id],
      name: 'payload_locked_documents_rels_colors_fk',
    }).onDelete('cascade'),
    originIdFk: foreignKey({
      columns: [columns['originID']],
      foreignColumns: [origin.id],
      name: 'payload_locked_documents_rels_origin_fk',
    }).onDelete('cascade'),
    discountsIdFk: foreignKey({
      columns: [columns['discountsID']],
      foreignColumns: [discounts.id],
      name: 'payload_locked_documents_rels_discounts_fk',
    }).onDelete('cascade'),
    ordersIdFk: foreignKey({
      columns: [columns['ordersID']],
      foreignColumns: [orders.id],
      name: 'payload_locked_documents_rels_orders_fk',
    }).onDelete('cascade'),
    shippingInfoIdFk: foreignKey({
      columns: [columns['shippingInfoID']],
      foreignColumns: [shipping_info.id],
      name: 'payload_locked_documents_rels_shipping_info_fk',
    }).onDelete('cascade'),
    paymentInfoIdFk: foreignKey({
      columns: [columns['paymentInfoID']],
      foreignColumns: [payment_info.id],
      name: 'payload_locked_documents_rels_payment_info_fk',
    }).onDelete('cascade'),
    reviewsIdFk: foreignKey({
      columns: [columns['reviewsID']],
      foreignColumns: [reviews.id],
      name: 'payload_locked_documents_rels_reviews_fk',
    }).onDelete('cascade'),
    'payload-jobsIdFk': foreignKey({
      columns: [columns['payload-jobsID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_locked_documents_rels_payload_jobs_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_user_accounts = relations(user_accounts, ({ one }) => ({
  userId: one(users, {
    fields: [user_accounts.userId],
    references: [users.id],
    relationName: 'userId',
  }),
}))
export const relations_user_sessions = relations(user_sessions, ({ one }) => ({
  userId: one(users, {
    fields: [user_sessions.userId],
    references: [users.id],
    relationName: 'userId',
  }),
}))
export const relations_user_verifications = relations(user_verifications, () => ({}))
export const relations_users_role = relations(users_role, ({ one }) => ({
  parent: one(users, {
    fields: [users_role.parent],
    references: [users.id],
    relationName: 'role',
  }),
}))
export const relations_users_rels = relations(users_rels, ({ one }) => ({
  parent: one(users, {
    fields: [users_rels.parent],
    references: [users.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [users_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  role: many(users_role, {
    relationName: 'role',
  }),
  _rels: many(users_rels, {
    relationName: '_rels',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_products_images = relations(products_images, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_images._parentID],
    references: [products.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [products_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_products_rating_distribution = relations(
  products_rating_distribution,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_rating_distribution._parentID],
      references: [products.id],
      relationName: 'ratingDistribution',
    }),
  }),
)
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  materialsID: one(materials, {
    fields: [products_rels.materialsID],
    references: [materials.id],
    relationName: 'materials',
  }),
  finishesID: one(finishes, {
    fields: [products_rels.finishesID],
    references: [finishes.id],
    relationName: 'finishes',
  }),
  categoriesID: one(categories, {
    fields: [products_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  variantsID: one(variants, {
    fields: [products_rels.variantsID],
    references: [variants.id],
    relationName: 'variants',
  }),
}))
export const relations_products = relations(products, ({ one, many }) => ({
  images: many(products_images, {
    relationName: 'images',
  }),
  origin: one(origin, {
    fields: [products.origin],
    references: [origin.id],
    relationName: 'origin',
  }),
  deity: one(deities, {
    fields: [products.deity],
    references: [deities.id],
    relationName: 'deity',
  }),
  ratingDistribution: many(products_rating_distribution, {
    relationName: 'ratingDistribution',
  }),
  seo_image: one(media, {
    fields: [products.seo_image],
    references: [media.id],
    relationName: 'seo_image',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}))
export const relations__products_v_version_images = relations(
  _products_v_version_images,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_images._parentID],
      references: [_products_v.id],
      relationName: 'version_images',
    }),
    image: one(media, {
      fields: [_products_v_version_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations__products_v_version_rating_distribution = relations(
  _products_v_version_rating_distribution,
  ({ one }) => ({
    _parentID: one(_products_v, {
      fields: [_products_v_version_rating_distribution._parentID],
      references: [_products_v.id],
      relationName: 'version_ratingDistribution',
    }),
  }),
)
export const relations__products_v_rels = relations(_products_v_rels, ({ one }) => ({
  parent: one(_products_v, {
    fields: [_products_v_rels.parent],
    references: [_products_v.id],
    relationName: '_rels',
  }),
  materialsID: one(materials, {
    fields: [_products_v_rels.materialsID],
    references: [materials.id],
    relationName: 'materials',
  }),
  finishesID: one(finishes, {
    fields: [_products_v_rels.finishesID],
    references: [finishes.id],
    relationName: 'finishes',
  }),
  categoriesID: one(categories, {
    fields: [_products_v_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
  variantsID: one(variants, {
    fields: [_products_v_rels.variantsID],
    references: [variants.id],
    relationName: 'variants',
  }),
}))
export const relations__products_v = relations(_products_v, ({ one, many }) => ({
  parent: one(products, {
    fields: [_products_v.parent],
    references: [products.id],
    relationName: 'parent',
  }),
  version_images: many(_products_v_version_images, {
    relationName: 'version_images',
  }),
  version_origin: one(origin, {
    fields: [_products_v.version_origin],
    references: [origin.id],
    relationName: 'version_origin',
  }),
  version_deity: one(deities, {
    fields: [_products_v.version_deity],
    references: [deities.id],
    relationName: 'version_deity',
  }),
  version_ratingDistribution: many(_products_v_version_rating_distribution, {
    relationName: 'version_ratingDistribution',
  }),
  version_seo_image: one(media, {
    fields: [_products_v.version_seo_image],
    references: [media.id],
    relationName: 'version_seo_image',
  }),
  _rels: many(_products_v_rels, {
    relationName: '_rels',
  }),
}))
export const relations_variants_images = relations(variants_images, ({ one }) => ({
  _parentID: one(variants, {
    fields: [variants_images._parentID],
    references: [variants.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [variants_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_variants = relations(variants, ({ one, many }) => ({
  product: one(products, {
    fields: [variants.product],
    references: [products.id],
    relationName: 'product',
  }),
  size: one(sizes, {
    fields: [variants.size],
    references: [sizes.id],
    relationName: 'size',
  }),
  color: one(colors, {
    fields: [variants.color],
    references: [colors.id],
    relationName: 'color',
  }),
  images: many(variants_images, {
    relationName: 'images',
  }),
}))
export const relations_sizes = relations(sizes, () => ({}))
export const relations_materials = relations(materials, () => ({}))
export const relations_finishes = relations(finishes, () => ({}))
export const relations_deities = relations(deities, () => ({}))
export const relations_categories = relations(categories, ({ one }) => ({
  parent: one(categories, {
    fields: [categories.parent],
    references: [categories.id],
    relationName: 'parent',
  }),
}))
export const relations_colors = relations(colors, () => ({}))
export const relations_origin = relations(origin, () => ({}))
export const relations_discounts_rels = relations(discounts_rels, ({ one }) => ({
  parent: one(discounts, {
    fields: [discounts_rels.parent],
    references: [discounts.id],
    relationName: '_rels',
  }),
  productsID: one(products, {
    fields: [discounts_rels.productsID],
    references: [products.id],
    relationName: 'products',
  }),
  categoriesID: one(categories, {
    fields: [discounts_rels.categoriesID],
    references: [categories.id],
    relationName: 'categories',
  }),
}))
export const relations_discounts = relations(discounts, ({ many }) => ({
  _rels: many(discounts_rels, {
    relationName: '_rels',
  }),
}))
export const relations_orders_items = relations(orders_items, ({ one }) => ({
  _parentID: one(orders, {
    fields: [orders_items._parentID],
    references: [orders.id],
    relationName: 'items',
  }),
  product: one(products, {
    fields: [orders_items.product],
    references: [products.id],
    relationName: 'product',
  }),
}))
export const relations_orders = relations(orders, ({ one, many }) => ({
  user: one(users, {
    fields: [orders.user],
    references: [users.id],
    relationName: 'user',
  }),
  items: many(orders_items, {
    relationName: 'items',
  }),
  shippingInfo: one(shipping_info, {
    fields: [orders.shippingInfo],
    references: [shipping_info.id],
    relationName: 'shippingInfo',
  }),
  paymentInfo: one(payment_info, {
    fields: [orders.paymentInfo],
    references: [payment_info.id],
    relationName: 'paymentInfo',
  }),
}))
export const relations_shipping_info = relations(shipping_info, ({ one }) => ({
  user: one(users, {
    fields: [shipping_info.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_payment_info = relations(payment_info, ({ one }) => ({
  user: one(users, {
    fields: [payment_info.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_reviews_images = relations(reviews_images, ({ one }) => ({
  _parentID: one(reviews, {
    fields: [reviews_images._parentID],
    references: [reviews.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [reviews_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_reviews_voted_users = relations(reviews_voted_users, ({ one }) => ({
  _parentID: one(reviews, {
    fields: [reviews_voted_users._parentID],
    references: [reviews.id],
    relationName: 'votedUsers',
  }),
  user: one(users, {
    fields: [reviews_voted_users.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_reviews = relations(reviews, ({ one, many }) => ({
  user: one(users, {
    fields: [reviews.user],
    references: [users.id],
    relationName: 'user',
  }),
  product: one(products, {
    fields: [reviews.product],
    references: [products.id],
    relationName: 'product',
  }),
  images: many(reviews_images, {
    relationName: 'images',
  }),
  votedUsers: many(reviews_voted_users, {
    relationName: 'votedUsers',
  }),
}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    'user-accountsID': one(user_accounts, {
      fields: [payload_locked_documents_rels['user-accountsID']],
      references: [user_accounts.id],
      relationName: 'user-accounts',
    }),
    'user-sessionsID': one(user_sessions, {
      fields: [payload_locked_documents_rels['user-sessionsID']],
      references: [user_sessions.id],
      relationName: 'user-sessions',
    }),
    'user-verificationsID': one(user_verifications, {
      fields: [payload_locked_documents_rels['user-verificationsID']],
      references: [user_verifications.id],
      relationName: 'user-verifications',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    variantsID: one(variants, {
      fields: [payload_locked_documents_rels.variantsID],
      references: [variants.id],
      relationName: 'variants',
    }),
    sizesID: one(sizes, {
      fields: [payload_locked_documents_rels.sizesID],
      references: [sizes.id],
      relationName: 'sizes',
    }),
    materialsID: one(materials, {
      fields: [payload_locked_documents_rels.materialsID],
      references: [materials.id],
      relationName: 'materials',
    }),
    finishesID: one(finishes, {
      fields: [payload_locked_documents_rels.finishesID],
      references: [finishes.id],
      relationName: 'finishes',
    }),
    deitiesID: one(deities, {
      fields: [payload_locked_documents_rels.deitiesID],
      references: [deities.id],
      relationName: 'deities',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    colorsID: one(colors, {
      fields: [payload_locked_documents_rels.colorsID],
      references: [colors.id],
      relationName: 'colors',
    }),
    originID: one(origin, {
      fields: [payload_locked_documents_rels.originID],
      references: [origin.id],
      relationName: 'origin',
    }),
    discountsID: one(discounts, {
      fields: [payload_locked_documents_rels.discountsID],
      references: [discounts.id],
      relationName: 'discounts',
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: 'orders',
    }),
    shippingInfoID: one(shipping_info, {
      fields: [payload_locked_documents_rels.shippingInfoID],
      references: [shipping_info.id],
      relationName: 'shippingInfo',
    }),
    paymentInfoID: one(payment_info, {
      fields: [payload_locked_documents_rels.paymentInfoID],
      references: [payment_info.id],
      relationName: 'paymentInfo',
    }),
    reviewsID: one(reviews, {
      fields: [payload_locked_documents_rels.reviewsID],
      references: [reviews.id],
      relationName: 'reviews',
    }),
    'payload-jobsID': one(payload_jobs, {
      fields: [payload_locked_documents_rels['payload-jobsID']],
      references: [payload_jobs.id],
      relationName: 'payload-jobs',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_products_status: typeof enum_products_status
  enum__products_v_version_status: typeof enum__products_v_version_status
  enum_discounts_type: typeof enum_discounts_type
  enum_discounts_applies_to: typeof enum_discounts_applies_to
  enum_orders_status: typeof enum_orders_status
  enum_reviews_voted_users_type: typeof enum_reviews_voted_users_type
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  user_accounts: typeof user_accounts
  user_sessions: typeof user_sessions
  user_verifications: typeof user_verifications
  users_role: typeof users_role
  users: typeof users
  users_rels: typeof users_rels
  media: typeof media
  products_images: typeof products_images
  products_rating_distribution: typeof products_rating_distribution
  products: typeof products
  products_rels: typeof products_rels
  _products_v_version_images: typeof _products_v_version_images
  _products_v_version_rating_distribution: typeof _products_v_version_rating_distribution
  _products_v: typeof _products_v
  _products_v_rels: typeof _products_v_rels
  variants_images: typeof variants_images
  variants: typeof variants
  sizes: typeof sizes
  materials: typeof materials
  finishes: typeof finishes
  deities: typeof deities
  categories: typeof categories
  colors: typeof colors
  origin: typeof origin
  discounts: typeof discounts
  discounts_rels: typeof discounts_rels
  orders_items: typeof orders_items
  orders: typeof orders
  shipping_info: typeof shipping_info
  payment_info: typeof payment_info
  reviews_images: typeof reviews_images
  reviews_voted_users: typeof reviews_voted_users
  reviews: typeof reviews
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_user_accounts: typeof relations_user_accounts
  relations_user_sessions: typeof relations_user_sessions
  relations_user_verifications: typeof relations_user_verifications
  relations_users_role: typeof relations_users_role
  relations_users_rels: typeof relations_users_rels
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_products_images: typeof relations_products_images
  relations_products_rating_distribution: typeof relations_products_rating_distribution
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations__products_v_version_images: typeof relations__products_v_version_images
  relations__products_v_version_rating_distribution: typeof relations__products_v_version_rating_distribution
  relations__products_v_rels: typeof relations__products_v_rels
  relations__products_v: typeof relations__products_v
  relations_variants_images: typeof relations_variants_images
  relations_variants: typeof relations_variants
  relations_sizes: typeof relations_sizes
  relations_materials: typeof relations_materials
  relations_finishes: typeof relations_finishes
  relations_deities: typeof relations_deities
  relations_categories: typeof relations_categories
  relations_colors: typeof relations_colors
  relations_origin: typeof relations_origin
  relations_discounts_rels: typeof relations_discounts_rels
  relations_discounts: typeof relations_discounts
  relations_orders_items: typeof relations_orders_items
  relations_orders: typeof relations_orders
  relations_shipping_info: typeof relations_shipping_info
  relations_payment_info: typeof relations_payment_info
  relations_reviews_images: typeof relations_reviews_images
  relations_reviews_voted_users: typeof relations_reviews_voted_users
  relations_reviews: typeof relations_reviews
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
